name: Pixel Pump Dev

on:
  push:
    branches:
      - dev

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: robin7331/micropython
        path: './micropython'
        ref: 'pixel-pump'
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git -y
    - name: Initialize MP submodules
      run: cd $GITHUB_WORKSPACE/micropython && git submodule update --init lib/pico-sdk lib/tinyusb
    - name: Build mpy-cross
      run: cd $GITHUB_WORKSPACE/micropython/mpy-cross && make
    - name: Build blank MicroPython firmware (without Pixel Pump files)
      run: |
        cd $GITHUB_WORKSPACE/micropython/ports/pixelpump
        make
        ls -l $GITHUB_WORKSPACE/micropython/ports/pixelpump/build-PICO
        mv $GITHUB_WORKSPACE/micropython/ports/pixelpump/build-PICO/firmware.uf2 $GITHUB_WORKSPACE/micropython/ports/pixelpump/build-PICO/firmware-blank.uf2 
    - name: Copy Pixel Pump firmware to micropython pixelpump port modules
      run: |
        cp -a $GITHUB_WORKSPACE/src/. $GITHUB_WORKSPACE/micropython/ports/pixelpump/modules/
    - name: Build MicroPython firmware
      run: |
        cd $GITHUB_WORKSPACE/micropython/ports/pixelpump
        make
        ls -l $GITHUB_WORKSPACE/micropython/ports/pixelpump/build-PICO
    - uses: marvinpinto/action-automatic-releases@latest
      name: Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Pixel Pump Dev Build"
        files: |
          micropython/ports/pixelpump/build-PICO/firmware.uf2
          micropython/ports/pixelpump/build-PICO/firmware-blank.uf2



