name: Pixel Pump Main

on:
  push:
    tags:
      - "v*"

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: robin7331/pixel-pump-micropython
        path: './micropython'
        ref: 'pixel-pump-main'
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git -y
    - name: Initialize MP submodules
      run: cd $GITHUB_WORKSPACE/micropython && git submodule update --init lib/pico-sdk lib/tinyusb
    - name: Build mpy-cross
      run: cd $GITHUB_WORKSPACE/micropython/mpy-cross && make
    - name: Build blank MicroPython firmware (without Pixel Pump files)
      run: |
        cd $GITHUB_WORKSPACE/micropython/ports/rp2
        make
        ls -l $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO
        mv $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO/firmware.uf2 $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO/firmware-blank.uf2 
    - name: Copy Pixel Pump firmware to micropython pixelpump port modules
      run: |
        cp -a $GITHUB_WORKSPACE/src/. $GITHUB_WORKSPACE/micropython/ports/rp2/modules/
    - name: Build MicroPython firmware
      run: |
        cd $GITHUB_WORKSPACE/micropython/ports/rp2
        make
        ls -l $GITHUB_WORKSPACE/micropython/ports/rp2/build-PICO
    - uses: marvinpinto/action-automatic-releases@latest
      name: Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        title: "Pixel Pump Release Build"
        files: |
          micropython/ports/rp2/build-PICO/firmware.uf2
          micropython/ports/rp2/build-PICO/firmware-blank.uf2



